CREATE DATABASE CompanyDb
GO
USE CompanyDb


CREATE TABLE Departments
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	ChangedAt DATETIME
)
GO

CREATE TABLE Employees
(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(40) NOT NULL,
	MiddleName NVARCHAR(40) NOT NULL,
	LastName NVARCHAR(40) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	Position NVARCHAR(40),
	ChangedAt DATETIME,
	HiredAt DATETIME,
	DepartmentId INT,
	FOREIGN KEY (DepartmentId) REFERENCES Departments (Id) ON DELETE CASCADE
)